server:
  port: 80
  undertow:
    io-threads: 1
    worker-threads: 4
    buffer-size: 1024
    buffers-per-region: 1024
    direct-buffers: true
spring:
  thymeleaf:
    cache: true
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.2.207:3306/module_basic?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: asd123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: false
  jpa:
    show-sql: false