server:
  port: 8081
  servlet:
    contextPath: /admin
  undertow:
    io-threads: 1
    worker-threads: 2
    buffer-size: 1024
    buffers-per-region: 1024
    direct-buffers: true
spring:
  thymeleaf:
    cache: false
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/jken
    username: sa
    password: sa
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true