spring:
  mvc:
    static-path-pattern: /**
  datasource:
    hikari:
      pool-name: blah
  h2:
    console:
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  messages:
    basename: i18n/message
  data:
    web:
      pageable:
        one-indexed-parameters: true
        page-parameter: page
        size-parameter: limit
  quartz:
    jobStoreType: JDBC